services:
  - type: web
    name: twitter-sentiment-analysis
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn MLapp:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18

